version: '2.2'
services:
  elasticsearch2:
    image: elasticsearch:7.4.0
    container_name: es74_03
    environment:
      - cluster.name=es-cluster
      - node.name=es74_03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms32768m -Xmx32768m"
      - discovery.seed_hosts=es74_01,es74_02,es74_03
      - network.publish_host=19.130.210.64
      - cluster.initial_master_nodes=es74_01,es74_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/:/usr/share/elasticsearch/data
    networks:
      - esnet
    extra_hosts:
      - "es74_01:19.130.210.58"
      - "es74_02:19.130.210.59"
      - "es74-03:19.130.210.64"
    ports:
      - 9200:9200
      - 9300:9300

# volumes:
#   esdata:
#     driver: local

networks:
  esnet:
    driver: bridge
